package dev.pluto.launcher.ui.overlay

/** Plain-English texts for the overlay layers (inline for 0.1; one place for later localisation). */
internal object OverlayText {
    // App actions
    const val APP_ACTIONS = "App actions"
    const val APP_MISSING = "This app is no longer available. It may have been uninstalled or disabled."
    const val LAUNCH = "Launch"
    const val PIN = "Pin to home"
    const val UNPIN = "Unpin from home"
    const val ADD_TO_DOCK = "Add to dock"
    const val REMOVE_FROM_DOCK = "Remove from dock"
    const val DOCK_FULL = "Dock is full. Remove an app from the dock first (Edit home)."
    const val CATEGORIES = "Categories…"
    const val MOVE_TO_FOLDER = "Move to folder…"
    const val HIDE = "Hide from launcher"
    const val HIDE_HINT = "Restore it any time from Settings ▸ Hidden apps"
    const val UNHIDE = "Show in launcher again"
    const val APP_INFO = "App info"
    const val UNINSTALL = "Uninstall…"
    const val UNINSTALL_HINT = "Android asks for confirmation"
    const val SUSPENDED = "Currently unavailable (paused or suspended)"
    fun inFolder(name: String) = "In folder “$name”"
    fun inCategories(names: List<String>) = if (names.isEmpty()) "Not in any category" else names.joinToString(", ")

    // Category membership
    const val CATEGORIES_TITLE = "Categories"
    const val NO_CATEGORIES = "There are no categories yet besides All apps."
    const val MANAGE_CATEGORIES = "Manage categories…"
    const val ALL_APPS_NOTE = "Every app is always in All apps."

    // Move to folder
    const val MOVE_TITLE = "Move to folder"
    const val NO_FOLDERS = "No folders yet. Create one below."
    const val NEW_FOLDER = "New folder…"
    const val NEW_FOLDER_TITLE = "New folder"
    const val FOLDER_NAME = "Folder name"
    const val DEFAULT_FOLDER_NAME = "Folder"
    const val CREATE = "Create"
    const val REMOVE_FROM_FOLDER = "Remove from folder"
    const val CURRENT_FOLDER = "Current folder"
    fun appCount(n: Int) = if (n == 1) "1 app" else "$n apps"

    // Edit
    const val EDIT_TITLE = "Edit home"
    const val EDIT_INTRO = "Select an item to move it, remove it or change it. Changes are saved immediately."
    const val HOME_SECTION = "Home favourites"
    const val HOME_EMPTY = "No favourites yet. Pin apps from their App actions menu."
    const val DOCK_SECTION = "Dock"
    const val FOLDERS_SECTION = "Folder contents"
    const val FOLDER_EMPTY = "This folder is empty."
    const val MOVE_UP = "Move up"
    const val MOVE_DOWN = "Move down"
    const val MOVE_BEFORE = "Move before…"
    const val MOVE_AFTER = "Move after…"
    const val RENAME_FOLDER = "Rename folder"
    const val DELETE_FOLDER = "Delete folder"
    const val DELETE_FOLDER_TEXT = "Apps in this folder go back to the home screen. No apps are uninstalled."
    const val DELETE = "Delete"
    const val RENAME = "Rename"
    const val ADD_APP_TO_SLOT = "Add app to this slot…"
    const val REPLACE_APP = "Replace app…"
    const val CHOOSE_APP = "Choose an app"
    const val NO_APPS = "No apps available."
    const val DONE = "Done"
    const val UNAVAILABLE_APP = "Unavailable app"
    fun dockSlot(slot: Int) = "Slot ${slot + 1}"
    const val EMPTY_SLOT = "Empty"
    fun moveBeforeTitle(name: String) = "Move “$name” before…"
    fun moveAfterTitle(name: String) = "Move “$name” after…"
    fun deleteFolderTitle(name: String) = "Delete folder “$name”?"
    fun folderHeader(name: String) = "Folder: $name"
    fun selectedHint(name: String) = "$name, selected. Controls follow."
}
